# -*- coding: utf-8 -*-
"""Combine_features.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X5Hpo60GCbln2t9s-uEVKh9mQKSYyGAf
"""

from google.colab import drive
drive.mount('/content/drive')

import os
# os.getcwd()
os.chdir('drive/My Drive/features')

import pickle as pk
f=open('tfidf_xtrain.pickle','rb')
tfidf_xtrain= pk.load(f)
f.close()

import pickle as pk
f=open('sentiment_train.pickle','rb')
sentiment_xtrain= pk.load(f)
f.close()

sentiment_xtrain.shape

import numpy as np
x= np.hstack((tfidf_xtrain,sentiment_xtrain))
print(x.shape)
# del(tfidf_xtrain)
# del(sentiment_xtrain)
# import gc
# collected= gc.collect()
# print("garbage collected= ",collected)

del(sentiment_xtrain)
import gc
collected= gc.collect()
print("garbage collected= ",collected)

x.shape

import pickle as pk
f=open('baseline_train.pickle','rb')
baseline_xtrain= pk.load(f)
f.close()

import numpy as np
x= np.hstack((x,baseline_xtrain))
print(x.shape)
del(baseline_xtrain)
import gc
collected= gc.collect()
print("garbage collected= ",collected)

import pickle as pk
f=open('wv_train.pickle','rb')
wv_xtrain= pk.load(f)
f.close()

import numpy as np
x= np.hstack((x,wv_xtrain))
print(x.shape)
del(wv_xtrain)
import gc
collected= gc.collect()
print("garbage collected= ",collected)

import pickle as pk
f=open('combined_feature_x.pickle','wb')
pk.dump(x,f)
f.close()
del(x)

import gc
collected= gc.collect()
print("garbage collected= ",collected)

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# 1. Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)  

# get the folder id where you want to save your file
file = drive.CreateFile()
file.SetContentFile('combined_feature_x.pickle')
file.Upload()
# del(x)
import gc
collected= gc.collect()
print("garbage collected= ",collected)

import pickle as pk
f=open('ytrain.pickle','rb')
ytrain= pk.load(f)
f.close()

sentiment_train, sentiment_val, wv_train, wv_val, base_train, base_val, trainLabels, valLabels = train_test_split(sentiment_train, wv_train, base_train, trainLabels, test_size=0.20, random_state=42)

from sklearn.model_selection import train_test_split
sentiment_train, sentiment_valid, wv_train, wv_valid, base_train, base_valid,tfidf_train,tfidf_valid, trainLabels, validLabels = train_test_split(sentiment_xtrain, wv_xtrain, baseline_xtrain, tfidf_xtrain,ytrain, test_size=0.20, random_state=42)

del(sentiment_xtrain)
del(wv_xtrain)
del(baseline_xtrain)
del(tfidf_xtrain)
del(ytrain)
import gc
collected= gc.collect()
print("garbage collected= ",collected)

sentiment_valid.shape

import os
os.mkdir('split')
os.chdir('split')

import pickle as pk
f=open('tfidf_train.pickle','wb')
pk.dump(tfidf_train,f)
f.close()

import pickle as pk
f=open('tfidf_valid.pickle','wb')
pk.dump(tfidf_valid,f)
f.close()

!pip install pydrive

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# 1. Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)  

# get the folder id where you want to save your file
file = drive.CreateFile()
file.SetContentFile('tfidf_train.pickle')
file.Upload()
# del(x)
import gc
collected= gc.collect()
print("garbage collected= ",collected)

import numpy as np
combined_xValid= np.hstack((tfidf_valid,sentiment_valid,base_valid,wv_valid))

import pickle as pk
f=open('combined_xvalid.pickle','wb')
pk.dump(combined_xValid,f)
f.close()

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# 1. Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)  

# get the folder id where you want to save your file
file = drive.CreateFile()
file.SetContentFile('combined_xvalid.pickle')
file.Upload()
# del(x)
import gc
collected= gc.collect()
print("garbage collected= ",collected)

del(combined_xTrain)
import gc
collected= gc.collect()
print("garbage collected= ",collected)

import numpy as np
combined_xValid= np.hstack((tfidf_valid,sentiment_valid,base_valid,wv_valid))

import pickle as pk
f=open('combined_xvalid.pickle','wb')
pk.dump(trainLabels,f)
f.close()